Igalia/webkit-container-sdk

docs/00-Introduction.md
Currently the `Quickstart guide` section in `docs/` has a broken formatting and outdated content (as compared to `README.md`) - see https://github.com/Igalia/wkdev-sdk/blob/main/docs/00-Introduction.md#quickstart-guide
Therefore in this PR I override the `Quickstart guide` section in `docs/` with contents of `Quickstart guide` section from `README.md` so that it looks correctly: https://github.com/Scony/wkdev-sdk/blob/fix-docs/docs/00-Introduction.md#quickstart-guide
=> Align 'Quickstart guide' in docs/ to the one in README.md

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
See https://github.com/WebPlatformForEmbedded/libwpe/releases/tag/1.14.2.
=> libwpe: switch to version 1.14.2, which contains a crash fix.

scripts/host-only/wkdev-enter
- Raise timeout from 10s -> 20s per retry (the jhbuild directory permission step takes a long time, depending on overlayfs performance).
- Actually honor the max-retries parameter - due to an oversight it always stopped at 10 retries.
- Document the failure case: how to investigate: podman logs -f <container_name>. Include that hint in the error message.
=> Improve wkdev-enter usability

.github/workflows/wkdev-sdk.yml, images/wkdev_sdk/Containerfile, images/wkdev_sdk/jhbuild/README.txt, scripts/host-only/wkdev-sdk-bakery
=> Attempt to build wkdev-sdk for multiple target platforms

images/wkdev_sdk/Containerfile, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules, images/wkdev_sdk/required_system_packages/01-base.lst, images/wkdev_sdk/required_system_packages/02-gcc.lst, images/wkdev_sdk/required_system_packages/03-clang.lst, scripts/container-only/wkdev-test-host-integration, utilities/nvidia-gpu.sh
Let's switch from Ubuntu 23.04 -> Ubuntu 24.04.
We need clang18 in the `wkdev-sdk` to be able to build latest WebKit with clang.
=> Update base SDK image to Ubuntu 24.04

images/wkdev_sdk/Containerfile, images/wkdev_sdk/required_system_packages/04-devtools.lst
The system provided Ubuntu v0.7.7 package is broken:
```
📦 nzimmermann@wkdev:~/$ cat foo.cpp
int foo() {{
📦 nzimmermann@wkdev:~/$ /usr/bin/sccache g++ -o foo.o -c foo.cpp foo.cpp: In function 'int foo()':
foo.cpp:1:13: error: expected '}' at end of input
1 | # 0 "foo.cpp"
|            ~^
foo.cpp:1:13: error: expected '}' at end of input
1 | # 0 "foo.cpp"
|           ~ ^
foo.cpp:1:13: warning: no return statement in function returning non-void [-Wreturn-type]
sccache: Compiler killed by signal 1
📦 nzimmermann@wkdev:~/$ /usr/bin/sccache g++ -o foo.o -c foo.cpp
📦 nzimmermann@wkdev:~/$
```
=> Build our own sccache v0.8.1 package.

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
This module moves fast enough that it is valuable for us to regularly test it in the SDK.
=> jhbuild: Build libsoup by default

images/wkdev_sdk/user_home_directory_defaults/dot-bash_profile, images/wkdev_sdk/user_home_directory_defaults/dot-zprofile, images/wkdev_sdk/user_home_directory_defaults/fish-config
This avoids the error message when installing python packages, that on Ubuntu you should install the python-xxxx packages instead of using pip3 install, if possible.
When that is set the error is suppressed, and one doesn't need to pass '--break-system-packages' to python manually.
=> Export PIP_BREAK_SYSTEM_PACKAGES=1 by default.

scripts/host-only/wkdev-create
To use an Xbox controller via libmanette, `/run/udev` needs to be mounted. Otherwise I see errors such as `openat(AT_FDCWD<..>, "/run/udev/data/c13:63", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)` and the gamepad isn't detected.
=> scripts: Mount /run/udev for gamepads

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Meson dependency is not needed in JHBuild modules since the version shipped by the underlying OS (currently, Ubuntu 24.04) is newer than the version stated in JHBuild modules file.
- JHBuild provided meson: 1.2.3
- System provided meson: 1.3.2
```bash
$ apt-cache madison meson
meson | 1.3.2-1ubuntu1 | http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages
meson | 1.3.2-1ubuntu1 | http://archive.ubuntu.com/ubuntu noble/universe Sources
```
```bash
$ git log -1 --pretty="%h %ad %ae %s" --date=short 1.2.3
84e437179 2023-10-17 nirbheek@centricul.. Bump versions to 1.2.3 for release
```
```bash
$ git log -1 --pretty="%h %ad %ae %s" --date=short 1.3.2
614d43623 2024-02-07 nirbheek@centricul.. Bump versions to 1.3.2 for release
```
=> jhbuild: remove meson

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules, images/wkdev_sdk/required_system_packages/04-devtools.lst
The prerequisite is to have sysprof installed on the host system, so that the container is able to talk to it via d-bus.
If that works, `sysprof-cli -- run-minibrowser` works out-of-the-box.
=> Add sysprof-47 (beta) support to wkdev-sdk.

.github/workflows/scripts/free_disk_space.sh, .github/workflows/wkdev-sdk.yml
The current `wkdev-sdk.yml` contains an action that frees up space in the GitHub Action CI worker. In addition to that, I want to try out another script that removes even more unnecessary stuff. If the gain is significant, we can keep it.
=> GitHub Actions: Free up more space in CI worker

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
There are modules that by default build examples, tests and tools. All these things are not necessary when building these libraries as subprojects. My goal disabling these features is to prevent the GitHub CI bot aborts due to lack of space, as it has happened in https://github.com/Igalia/webkit-container-sdk/pull/39
=> jhbuild: disable examples, tests and tools in modules whenever possible

images/wkdev_sdk/Containerfile, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules, images/wkdev_sdk/required_system_packages/04-devtools.lst, scripts/container-only/.wkdev-init, scripts/container-only/wkdev-test-host-integration
This PR updates JHBuild's gstramer to the same version as Flatpak: 1.24.6. Also, now GStreamer modules 'rs' (Rust) and 'webrtc' are enabled.
When the 'rs' module is enabled, compilation fails with the following error:
```bash
../subprojects/gst-plugins-rs/meson.build:28:2: ERROR: Problem encountered: cargo-c missing, install it with: 'cargo install cargo-c'
A full log can be found at /home/buildbot/workspace/gstreamer/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
main buildbot@wkdev ~/workspace/gstreamer/build $ cargo install cargo-c
Updating crates.io index
error: cannot install package `cargo-c 0.10.3+cargo-0.81.0`, it requires rustc 1.78 or newer, while the currently active rustc …
```
=> jhbuild: update gstreamer to 1.24.6

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Spiel is a nicer alternative to Festival for speech synthesys because its API is directly inspired from WebSpeech. A future patch will rewrite our speech synthesys backend using Spiel, but we first need it in the SDK. The host is responsible for installing voice providers using Flatpak, so this part is not included in this patch.
=> jhbuild: Add libspiel

scripts/container-only/.wkdev-init
1. No more progress messages:
[4/14]
[5/14]
[6/14]
[7/14]
-> /etc/subgid contents: nzimmermann:50000:50000
-> /etc/subuid contents: nzimmermann:50000:50000
2. Broken symlink, due to wrong s/log/task_step/ replacement.
sudo: unable to resolve host wkdev.nzimmermann-thinkpad: Name or service not known ln: failed to create symbolic link '/dev/task_step': Permission denied [8/14]
[9/14]
[10/14]
[11/14]
[12/14]
3. Missing task_step usage (wrong counter, 14 steps not 13).
[12/13] Setup rust '/opt/rust' directory permissions...
=> Unbreak .wkdev-init script.

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Switch to new libwpe/wpebackend-fdo releases, upgrade libdex/libpanel/etc.
Make sure to always attach tags to checkouts, to guarantee a certain version is used, independant of the image build time (where possible).
This includes the PR #50, and needs to rebased, once it's merged to main.
=> Upgrade jhbuild dependencies

.github/workflows/wkdev-sdk.yml
Right now, the free GitHub runner is failing in `deploy` step due to lack of space in the runner:
- https://github.com/Igalia/webkit-container-sdk/actions/runs/11069214537
We would like to switch the runner to self-hosted so we can have more storage space in the container.
=> [CI] Switch runner to self-hosted

scripts/host-only/wkdev-enter
Show an excerpt from the container log after waiting for N seconds to try to enter the container.
This helps the user to indicate progress, when entering a freshly created container for the first time (when wkdev-init is running for the first time). At the same time, no output is shown upon successive wkdev-enter commands, since the container is already initialized, and entering it is fast by definition.
=> wkdev-enter: Show container log, while waiting for initialization

scripts/host-only/wkdev-update
Fixes issue #55. Remove the --verbose option, and make it default.
This avoids surprises, when the script appears to be stuck, when it's e.g. pulling a new image from ghcr.io -- always show the podman pull output instead.
=> wkdev-update: Make --verbose the default mode.

scripts/container-only/.wkdev-init
This fixes cases where the symbolic link is already present in the system, such as in the latest Ubuntu images.
If `/dev/log` already exists, the script skips the link creation to avoid the following error message:
```
[9/14] Set /dev/log symbolic link to /run/systemd/journal/dev-log ...
ln: failed to create symbolic link '/dev/log': Permission denied
```
Issue: https://github.com/Igalia/webkit-container-sdk/issues/49
=> Improve /dev/log symbolic link setup to only create it if missing (#49)

images/wkdev_sdk/Containerfile, images/wkdev_sdk/jhbuild/patches/0001-webrtcbin-create-and-associate-transceivers-earlier-.patch, images/wkdev_sdk/jhbuild/patches/0002-webrtcbin-reverse-direction-from-remote-media.patch, images/wkdev_sdk/jhbuild/patches/0003-webrtcbin-connect-output-stream-on-recv-transceivers.patch, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Those will not ship until 1.26.
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7156 https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7294
=> jhbuild: Backport webrtc patches from GStreamer main branch

scripts/container-only/wkdev-sdk-show-welcome-message, scripts/container-only/wkdev-setup-devhelp, scripts/container-only/wkdev-setup-sccache, scripts/container-only/wkdev-setup-vscode, scripts/container-only/wkdev-test-host-integration, scripts/host-only/wkdev-create, scripts/host-only/wkdev-enter, scripts/host-only/wkdev-sdk-bakery, scripts/host-only/wkdev-setup-nvidia-gpu-for-container, scripts/host-only/wkdev-update, utilities/cpu-profiling.sh, utilities/host-setup-tasks.sh
This makes it easier to disable logging messages with new --quiet options or to use syslog/journald in the future.
=> Use _log_ instead of echo for logging messages

images/wkdev_sdk/Containerfile, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Follow-up to: [jhbuild: update gstreamer to 1.24.6](https://github.com/Igalia/webkit-container-sdk/pull/39)
=> jhbuild: build gstreamer plugin 'dav1ddec'

.gitignore
That file is created by wkdev-start-profiling and should not be checked in the repository.
=> .gitignore: .sysctl_setting_perf_event_paranoid

scripts/container-only/.wkdev-sync-runtime-state
I missed this file when working on
https://github.com/Igalia/webkit-container-sdk/pull/64 due to ripgrep excluding hidden files by default.
=> .wkdev-sync-runtime-state: use _log_

scripts/container-only/.wkdev-sync-runtime-state, scripts/host-only/wkdev-enter, utilities/application.sh
This patch adds an optional --quiet flag for wkdev-enter that suppresses logging to stdout, so that scripts can be written that use wkdev-enter without pollution from wkdev logs.
The _log_ function now calls the logger command that writes to journald. This is meant to help with troubleshooting scripts that use the quiet mode.
This patch also adds the flags --no-tty and --no-interactive, which disable --tty and --interactive in podman exec respectively, and are of interest in scripts.
=> wkdev-enter: quiet mode and related options for scripts

images/wkdev_sdk/jhbuild/patches/0004-pad-Never-push-sticky-events-in-response-to-a-FLUSH_.patch, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Applies https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7632 on top of stable GStreamer. That merge request fixes a long standing race condition prone to occur in MSE.
=> Forward port GStreamer sticky events race fix

utilities/podman.sh
systemctl status can be noisy if the log has been rotated, showing this message:
> Warning: The unit file, source configuration file or drop-ins of
> podman.socket changed on disk. Run 'systemctl --user daemon-reload'
> to reload units.
This can be especially problematic in --quiet mode. This patch fixes that by redirecting stderr of the systemctl call used to get the running state of podman to /dev/null.
=> Silence systemctl messages

images/wkdev_sdk/jhbuild/patches/0001-webrtcbin-create-and-associate-transceivers-earlier-.patch, images/wkdev_sdk/jhbuild/patches/0002-webrtcbin-reverse-direction-from-remote-media.patch, images/wkdev_sdk/jhbuild/patches/0003-webrtcbin-connect-output-stream-on-recv-transceivers.patch, images/wkdev_sdk/jhbuild/patches/0004-webrtc-Fixes-for-matching-pads-to-unassociated-trans.patch, images/wkdev_sdk/jhbuild/patches/0005-webrtcbin-Fix-renegotiation-checks.patch, images/wkdev_sdk/jhbuild/patches/0006-webrtc-add-all-SSRC-attributes-getting-CAPS-for-a-PT.patch, images/wkdev_sdk/jhbuild/patches/0007-rtpfunnel-also-fallback-to-pad-default-handling-for-.patch, images/wkdev_sdk/jhbuild/patches/0008-webrtcbin-enable-forward-unknown-ssrc-on-rtpfunnel.patch, images/wkdev_sdk/jhbuild/patches/0009-rtpfunnel-Ensure-segment-events-are-forwarded-after-.patch, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Out of the list only
0009-rtpfunnel-Ensure-segment-events-are-forwarded-after-.patch is going to ship in 1.24(.10). The others will ship in 1.26.
=> gstreamer: Include additional patches

images/wkdev_sdk/Containerfile, images/wkdev_sdk/required_system_packages/04-devtools.lst, scripts/host-only/wkdev-sdk-bakery, utilities/resources.sh
Contains a few individual changes, needed for the bot/infrastructure migration.
=> Modify container image for bots/infrastructure migration

.github/workflows/wkdev-sdk.yml
Clear all the podman images/containers as first step in the CI process.
This assumes, we don't have any concurrent SDK CI builds on the machine that hosts the runner. This holds true, and avoid piling up disk space for dangling images.
=> Add prune step to CI

.github/workflows/wkdev-sdk.yml
GITHUB_ENV needs to be used to set environment variables, not GITHUB_OUTPUT. The key/value pairs are also propagated to the following steps, so it works.
=> Fix setting environment vars in GitHub workflow.

images/wkdev_sdk/Containerfile, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
livesync is no longer needed. fmp4 might be used in the MediaRecorder backend.
=> gst-plugins-rs: Enable fmp4 and disable livesync

README.md, docs/00-Introduction.md, docs/04-Cross-compilation-inside-the-SDK.md
Fixed a couple of typos / misspellings, and clarified a paragraph about checking the container had been successfully setup
=> docs: Fix typos and clarify verification step

images/wkdev_sdk/Containerfile, scripts/host-only/wkdev-create, scripts/host-only/wkdev-sdk-bakery
This adds a -arch option for building and running the container image.
This was tested with qemu, building an armv7 image for intel. The goal however is to use it for armv7 on arm64.
When building for armv7, rustup was not found. This installs it in the containerfile as a workaround, although I am not sure how this ever worked. It would be nice to provide pre-built armv7 (and perhaps riscv) images.
=> Add support for running containers with foreign architectures

images/wkdev_sdk/Containerfile
Didn't try this but it should work, given cargo supports version 0.9.1.
The latter is confirmed by `cargo info sccache`.
This potentially fixes incremental build bugs for WebKit, see
<https://bugs.webkit.org/show_bug.cgi?id=286676>.
=> Update sccache version to 0.9.1

images/wkdev_sdk/Containerfile, scripts/container-only/wkdev-setup-default-clang
This allows easily installing and switching between different clang toolchains
=> Add wkdev-setup-default-clang script

images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules
Including a critical security fix (https://github.com/cisco/openh264/security/advisories/GHSA-m99q-5j7x-7m9x)
=> jhbuild: Bump to openh264 2.6.0

images/wkdev_sdk/Containerfile, images/wkdev_sdk/required_system_packages/04-devtools.lst, images/wkdev_sdk/required_system_packages/05-armv7-jhbuild.lst
Rustup is not available on armv7, so we install rust manually.
We also add some missing dependencies
=> Armv7-build-fix

scripts/host-only/wkdev-create
* When running inside LXC do not manually mount `/dev/pts` and let Podman figure this out. Otherwise this causes a fatal error when starting the container because it can't access `/dev/pts/$N`. Related issue: https://github.com/89luca89/distrobox/issues/688
* Also do not try to bind-mount `/run/udev` if is not available.
=> Fix issues when running inside a LXC container.

scripts/host-only/wkdev-create, scripts/host-only/wkdev-enter, utilities/application.sh, utilities/podman.sh
podman start gives reasonably good error messages, but they're currently being lost as the command is run silently.
This patch adds a new function to run commands silently but storing their stderr output to report it in case of an error.
As a drive-by fix, this patch also fixes some quoting issues in wkdev-create.
Fixes https://github.com/Igalia/webkit-container-sdk/issues/35
=> Print errors from podman start

.github/workflows/wkdev-sdk.yml, scripts/host-only/wkdev-create, scripts/host-only/wkdev-sdk-bakery
For now, we only build the intel image. I have locally tested that this works with arm64 too.
- Always tag images, so that we can easily tar and untar them
- Download images from the build${arch} job, and create a multi-arch manifest
=> Support multi-arch builds with separate workers

images/wkdev_sdk/Containerfile
[Pin rust version to prevent rust updates from breaking the build.](https://github.com/Igalia/webkit-container-sdk/pull/110/commits/21b7660db5c9b45bb71211cf1357a227b98137a6)
=> Pin rust version

images/wkdev_sdk/Containerfile, images/wkdev_sdk/rootfs/etc/apt/sources.list.d/llvm.list, scripts/container-only/wkdev-setup-default-clang
This allows for easily installing Clang 20
=> image: Add LLVM APT repo

scripts/host-only/wkdev-enter
In current versions of podman at least, podman inspect returns empty stdout if the container doesn't exist, not the string "unknown".
=> wkdev-enter: Fix broken missing container detection

images/wkdev_sdk/Containerfile, images/wkdev_sdk/jhbuild/webkit-sdk-deps.modules, images/wkdev_sdk/required_system_packages/01-base.lst
Otherwise openh264 is selected for GStreamer layout tests and that encoder is not as functional as x264enc which is also currently selected by default in the legacy SDK.
=> Add x264 to system dependencies

images/wkdev_sdk/Containerfile, images/wkdev_sdk/required_system_packages/01-base.lst
This is needed mostly for webcodecs tests.
=> Add x265 to system dependencies

.github/workflows/wkdev-sdk.yml
The arm64 machine isn't working because of some disk issues, let's use the working intel machine for now.
=> Use intel worker for deploy phase

.github/workflows/wkdev-sdk.yml, scripts/host-only/wkdev-sdk-bakery
Podman deletes the underlying linked images when we delete the latest tag. We end up getting:
Load/replace latest_arm64
Load/replace latest_amd64
Delete latest (deletes latest_arm64 and latest_amd64)
Create latest
Add latest_amd64 (fails)
Instead, we should delete the existing images and the latest manifest first.
=> Delete existing images before loading

images/wkdev_sdk/user_home_directory_defaults/dot-gdbinit
After attaching to WPEWebProcess, gdb would halt all the time at SIGUSR1. Make sure to set the SIGUSR1 handler to 'nostop' so it doesn't halt in gdb everytime it fires (JSC uses this for GC internally).
=> Modify our .gdbinit default file, to handle SIGUSR1.

images/wkdev_sdk/required_system_packages/01-base.lst
This is needed for tools like monado
=> Add vulkan to system dependencies

.github/workflows/wkdev-sdk.yml
The 'create' workflow trigger was firing for all branch creations, including PR branches, causing unnecessary workflow runs. GitHub Actions does not support filtering the 'create' event at the trigger level.
Added job-level conditionals to all 4 jobs to skip execution when the event is 'create' and the branch name does not start with 'tag/'. This preserves the auto-trigger functionality for tag branches (e.g., tag/23.04) while preventing workflows from running on regular branch creation.
=> Filter 'create' event to only trigger for tag/ branches
